package leetcode;

import java.util.*;

// https://leetcode.com/problems/find-the-difference/description/

// Given two strings s and t which consist of only lowercase letters.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.
public class FindTheDifference {
    public char findTheDifference(String s, String t) {

        // only lowercase letters
        int[] charsInS = new int[26];
        // int[] charsInT = new int[26];

        for (char c : s.toCharArray()) {
            charsInS[c-'a']++;
        }

        for (char c : t.toCharArray()) {
            charsInS[c-'a']--;
            if (charsInS[c-'a'] < 0) {
                return c;
            }
        }

        // for (char c : t.toCharArray()) {
        //     charsInT[c-'a']++;
        // }
        //
        // for (int i = 0; i < 26; i++) {
        //     if (charsInS[i] != charsInT[i]) {
        //         return (char)('a' + i);
        //     }
        // }
        return ' ';
    }
}
